apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim
  namespace: smartm2m
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
